spring:
  application:
    name: student-service
    cloud:
      config:
        uri:  http://localhost:8888

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8700/eureka/