server:
  port: ${PORT:0}
spring:
  application:
    name: admission-service
  data:
    cassandra:
      keyspace-name: royforthewin
      port: 9042
      contact-points: localhost
      username: cassandra
      password: cassandra

eureka:
  client:
    registry-fetch-inteval-seconds: 5
    service-url:
      defaultZone: http://localhost:8700/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"